### PR TITLE
Replace with (very slow) ATDIS feed

### PR DESCRIPTION
**Pull request by CloCkWeRX**
I'm in two minds about this.

The service works; though takes minutes to cough up a response:

```
$ wget http://datracker.begavalley.nsw.gov.au/ATDIS/1.0/applications.json
--2016-03-21 15:37:22--  http://datracker.begavalley.nsw.gov.au/ATDIS/1.0/applications.json
Resolving datracker.begavalley.nsw.gov.au (datracker.begavalley.nsw.gov.au)... 220.101.81.225
Connecting to datracker.begavalley.nsw.gov.au (datracker.begavalley.nsw.gov.au)|220.101.81.225|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: 'applications.json’

applications.json               [ <=>                                          ]  11.84K  72.2KB/s   in 0.2s   

2016-03-21 15:38:31 (72.2 KB/s) - 'applications.json’ saved [12125]
```

However, due to #4 this isn't working at all.

On my local, 

```
$ bundle exec ruby scraper.rb
/home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:427:in `rescue in transmit': Request Timeout (RestClient::RequestTimeout)
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/atdis-0.3.13/lib/atdis/model.rb:73:in `read_url'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/atdis-0.3.13/lib/atdis/feed.rb:62:in `applications'
    from /home/clockwerx/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/atdisplanningalertsfeed-ce20de6801cf/lib/atdisplanningalertsfeed.rb:11:in `save'
    from scraper.rb:6:in `<main>'
```

but presumably if some kind of extended timeout could be set (haven't looked at it too much); or we can ask the council to investigate performance.

### CODE REVIEW

**Comment by henare** [comment]
Since I can't get this to work locally it means this unfortunately isn't a fix so I'm not going to merge it until we can work out a way to get it to work.

**Comment by CloCkWeRX** [comment]
Email sent

```
Subject: Problem with development application server
To: council@begavalley.nsw.gov.au

Hi,
You might want to pass this onto your IT department or product vendor.

While the DA tracker works well through the web interface (http://datracker.begavalley.nsw.gov.au/Home/Index) it is very slow via the ATDIS interface.

$ time curl "http://datracker.begavalley.nsw.gov.au/ATDIS/1.0/applications.json?lodgement_date_start=2016-03-01&lodgement_date_end=2016-04-01"

real    1m14.417s
user    0m0.012s
sys 0m0.004s

Usually, this is just a missing DB index or a slightly different query in use from what the web results provide.

At the moment it's preventing some planning applications from being indexed on sites like planningalerts.org.au - a not for profit service to email people about new developments in their area.
```

**Comment by henare** [comment]
@CloCkWeRX did you ever hear back from the authority or is their email response time even slower than their server response time? \*rimshot\*

**Comment by henare** [comment]
I've made this work by adding an extended timeout as @CloCkWeRX suggested. I couldn't add commits to this PR so I've opened #4 and will close this.

**Pull request closed without merging**
